Add weekStartsOn prop
computerjazz/react-native-swipe-calendar pull request #2
Opened 2022-02-17 21:31 UTC by thecoorum

## Description
This PR adds `weekStartsOn` prop to define what day index the week should start

2022-02-18 00:16 UTC, computerjazz commented on src/Month.tsx
>      [firstDayOfMonth, lastDayOfMo]
please add `weekStartsOn` to dependency array

2022-02-18 00:16 UTC, computerjazz requested changes
looks great, thanks! just one small change

2022-02-18 17:18 UTC, computerjazz commented
Thank you! I'm assuming if `weekStartsOn` is undefined the default (Sunday/0) will apply?

2022-02-18 17:19 UTC, merged

2022-02-19 10:43 UTC, thecoorum commented
> Thank you! I'm assuming if `weekStartsOn` is undefined the default (Sunday/0) will apply?

Yes, this is what official docs of date-fns says